spring:
  datasource:
    url: 'jdbc:postgresql://db:5432/BCB?createDatabaseIfNotExist=true'
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: 'classpath:db/dbchanges.xml'
bigchatbrasil:
  message:
    cost: 0.25
