spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BCB
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
liquibase:
  change-log: classpath:/db/changelog/changelog-master.xml
bigchatbrasil:
  message:
    cost: 0.25