version: '3.1'
services:
  db:
    image: postgres
    container_name: DbPostgres
    environment:
      POSTGRES_DB: BCB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - compose-bridge  
    ports:
      - 6543:5432

  app:
    image: openjdk:17-jdk-slim
    volumes:
      - ./BigChatBrasil.jar:/app/app.jar
    command: ["java", "-jar", "/app/app.jar"]
    container_name: BCBApi
    networks:
      - compose-bridge
    ports:
      - 8080:8080 
    depends_on:
      - db 
    restart: on-failure
   
networks:
  compose-bridge:
    driver: bridge    
